### ISSUE TITLE
Update PyDreamScreen at pypi

### ISSUE THREAD

**Issue by J3n50m4t** [GregoryDosh/pydreamscreen#2]
Over at Homeassistant Dreamscreen user experience Issues due to outdated pydreamscreen.
Homeassistant automatically pulls pydreamscreen but my latest changes aren't implemented yet. 
So how can i update pydreamscreen there? 
https://pypi.org/project/PyDreamScreen/

**Comment by GregoryDosh** [comment]
I've uploaded the most recent build of PyDreamScreen (ver 0.0.10) and it should be available.  I'll be finally getting my DreamScreen and home stuffs back in the middle end of August so I can be more available for issues and updates.  Thanks again @J3n50m4t for keeping an eye out.

**Comment by J3n50m4t** [comment]
Mmh doesn't seem to work. Latest release is still 9. May.
Could you add me as a Maintainer there, so i can upload later versions? Also i bumped the version to 0.0.11 - so there should be some changes to upload now.

**Comment by GregoryDosh** [comment]
Yup, I looked before into adding you but I don't think I was able to find your same username before. What's your name to add?

**Comment by J3n50m4t** [comment]
J3n50m4t
Didn’t exist few hours ago 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GregoryDosh** [comment]
@J3n50m4t should be done, let me know if it didn't catch up.  In other side news I should be getting my TV and DreamScreen back in the next 1-2 weeks (waiting on movers).  So I should be more active then.
